### ISSUE TITLE
UI is not much user friendly.

### ISSUE THREAD

**Issue by shivamverma020** [The-Nightwing/Craigslist-Clone#2]
All the frontend files are in the templates and static folder, make changes in them and make the frontend more user friendly.

**Comment by mrpeterli** [comment]
Hi, I have a recommended change.

Changed Submit to Search as it makes it clearer to users that they are searching instead of submitting something. Additionally, I made the search button Green as it pops out more to the user.

**Comment by mrpeterli** [comment]
Is it possible to help me out by adding "hacktoberfest-accepted" label to my PR? Thank you!

**Comment by shivamverma020** [comment]
> Is it possible to help me out by adding the "hacktoberfest-accepted" label to my PR? Thank you!

Hey Peter, yeah I can do that. But the changes done by you are not giving that much effect to the website. Try applying some more front-end material, for example, a background, change in form, colors on the website, beautify the navbar and the whole page, etc. This issue doesn't asks for a lot. If you are able to beautify the website a little more I can give you the label.
